### ISSUE TITLE
Missing info / broken link in user.py section of README

### ISSUE THREAD

**Issue by hack-r** [OpenBCI/OpenBCI_Python#47]
Hi,

I thought I'd mention that in the [README](https://github.com/OpenBCI/OpenBCI_Python) when you get to the **user.py** section it assumes that you've connected to the board via Bluetooth, and references a broken (re-directed) link on how to do so (http://docs.openbci.com/tutorials/01-GettingStarted). 

My assumption is that the linked resource was replaced with the board-specific versions thereof, but (http://docs.openbci.com/Tutorials/02-Ganglion_Getting%20Started_Guide) I didn't see instructions in the board-specific getting started sections on how to connect via bluetooth and find a dev path like the one in your example.

On a tangentially related note, it might be worth noting that you can't use the `pip install` version of `bluepy` because then `from btle` won't work (I can go into more detail if needed).

**Comment by jfrey-xx** [comment]
Hello,

In the paragraph you mention, the broken "Getting started" link should refer to the Cyton.

For the ganglion, instead of modifying the source code, did you try to clone the repository with `--recursive" and type `make` as instructed by both the readme and #36 that you referred at first? You edited you message I think, do you confirm that you don't have any error by using the pip version of bluepy (you reported a `NameError: name 'DefaultDelegate' is not defined` before)?

**Comment by hack-r** [comment]
Hi,

Yes thanks very much. I did find that it works without editing the file if bluepy is not installed from pip. I edited the Issue to remove that comment but you probably got the original version of my question by email.

Regarding the bluetooth connection - do you mean the part of the Cyton tutorial that refers to a built-in RFDuino? Since the Ganglion has Simplebee instead of RFduino, is it still possible to connect via bluetooth? Do you know if there's any example out there? It would be an awesome thing to add to the README but I know you are very busy.

Thanks again.

**Comment by jfrey-xx** [comment]
I added you this example to the README. The problem is that the README was written mostly for the Cyton and "patched" for the Ganglion, it should be reworked to better split Cyton / Ganglion when the usage differs. 

Regarding my previous comment, the broken link belonged to an example that is meant for the Cyton, I took from granted that from the point of view of the computer it's "talking" to a serial pot, indeed bluetooth is only meaningful with the Ganglion (even if, *in theory* there is a BLE mode with the Cyton, that to my knowledge nobody really implemented).
