### ISSUE TITLE
Trouble connecting python to LSL

### ISSUE THREAD

**Issue by digitalgreentea** [OpenBCI/OpenBCI_Python#64]
When I run:

`python openbci_lsl.py --stream`

it outputs the following:

-------INSTANTIATING BOARD-------
Traceback (most recent call last):
  File "openbci_lsl.py", line 56, in <module>
    main(sys.argv[1:])
  File "openbci_lsl.py", line 40, in main
    lsl = streamerlsl.StreamerLSL(GUI=False)
  File "C:\Program Files\MATLAB\OpenBCI_LSL\lib\streamerlsl.py", line 46, in __init__
    self.initialize_board(autodetect=True)
  File "C:\Program Files\MATLAB\OpenBCI_LSL\lib\streamerlsl.py", line 59, in initialize_board
    self.board = bci.OpenBCIBoard()
  File "C:\Program Files\MATLAB\OpenBCI_LSL\lib\open_bci_v3.py", line 77, in __init__
    port = self.find_port()
  File "C:\Program Files\MATLAB\OpenBCI_LSL\lib\open_bci_v3.py", line 599, in find_port
    raise OSError('Cannot find OpenBCI port')
OSError: Cannot find OpenBCI port

Where can I find the [port] for my device? I have a Ganglion.

Also, how do I change the init function in open_bci_v3.py to establish a serial connection in Windows?

**Comment by jfrey-xx** [comment]
`openbci_lsl.py` does not belong to this repository -- here you have to load LSL plugin to activiate it.

[already answered via e-mail for the part below, copying for others]

You are using windows, however at the moment only linux is supported, due to the python library used to handle BLE connections. Sorry :\

If case you want to give Linux a try (through a virtual machine or by installing a distribution on a live usb key for exemple), you have to specify the "port" option... which for the Ganglion is not *really* a port, it is the MAC address of the device, that you should see when you can for bluetooth devices on your machine. If you don't specify the MAC address the script will try to auto-detect it, but it could fail.
